import {useState,useEffect,useRef} from 'react';
import snapshot from '../data/offers.json';
import type {Offer,Filters,Product} from './types';
import {results,group,b4b,discount,savings,decision,selectCompare,buyable} from './lib/board';
const offers=snapshot.offers as Offer[];
const categories=['Wszystkie','IEM','TWS','Closed','Głośniki BT'];
const defaults:Filters={search:'',category:'Wszystkie',conditions:[],region:'Wszystkie',status:'Wszystkie',liveOnly:true,history:false,sort:'b4b'};
function read(){try{return {...defaults,...JSON.parse(localStorage.getItem('audio-board')||'{}')}}catch{return defaults}}
const money=(n:number|null)=>n===null?'Brak danych':new Intl.NumberFormat('pl-PL',{style:'currency',currency:'PLN',maximumFractionDigits:2}).format(n);
const pct=(n:number|null)=>n===null?'Brak benchmarku':(n>0?'+':'')+(n*100).toFixed(1)+'%';
function Source({offer,primary=false}:{offer:Offer;primary?:boolean}){return <div className={'source '+(offer.status==='HISTORICAL'?'historical':'')} data-testid="source-row"><b>{offer.status==='HISTORICAL'?'HISTORICAL':primary?'PRIMARY':offer.role==='OFFER'?offer.condition==='NEW'?'NEW COMP':'USED COMP':offer.role}</b><strong>{money(offer.price)}</strong><span>{offer.seller}<small>{offer.country} / {offer.condition}</small></span><span className="status">{offer.status}</span><a href={offer.url} target="_blank" rel="noopener noreferrer" aria-label={'Otwórz źródło: '+offer.model+' · '+offer.seller+' · '+offer.condition}>Otwórz ↗</a><small className="source-note">{offer.note}<span> · Zapis SSOT: {offer.checked} · Cena oryginalna: {offer.original}</span></small></div>}
function Prices({o}:{o:Offer}){return <><div className="prices"><div><span>RYNEK NOWE</span><strong>{money(o.newMarket)}</strong></div><div><span>RYNEK TEGO SAMEGO STANU · {o.condition}</span><strong>{money(o.sameMarket)}</strong></div><div className="offer-price"><span>{buyable(o)?'NAJLEPSZA KONKRETNA OFERTA':'ŹRÓDŁO WARUNKOWE / BENCHMARK'}</span><strong>{money(o.price)}</strong><small>{o.seller} · {o.country} · {o.condition}</small></div></div><div className="metrics"><span>Taniej vs ten sam stan <b>{pct(discount(o))}</b></span><span>Taniej vs nowe <b>{pct(savings(o))}</b></span><span>MSRP / RRP <b>{money(o.rrp)}</b></span></div></>}
export default function App(){
const [f,setF]=useState<Filters>(read);const [density,setDensity]=useState(()=>{try{return localStorage.getItem('audio-density')||'Comfortable'}catch{return 'Comfortable'}});
const [selected,setSelected]=useState<string[]>([]);const [message,setMessage]=useState('');const [comparison,setComparison]=useState(false);const dialog=useRef<HTMLDialogElement>(null);const compareButton=useRef<HTMLButtonElement>(null);
useEffect(()=>{try{localStorage.setItem('audio-board',JSON.stringify({category:f.category,sort:f.sort,liveOnly:f.liveOnly}));localStorage.setItem('audio-density',density)}catch{/* Storage can be unavailable in private browsing. */}},[f,density]);
useEffect(()=>{if(comparison)dialog.current?.showModal();else dialog.current?.close()},[comparison]);
const change=<K extends keyof Filters>(key:K,value:Filters[K])=>setF(x=>({...x,[key]:value}));
const products=results(offers,f); const all=group(offers);const compare=all.filter(p=>selected.includes(p.model));
function toggle(model:string){const result=selectCompare(selected,model);setSelected(result.ids);setMessage(result.error)}
function product(p:Product,i:number){return <article key={p.model} className="product" data-testid="product"><header className="product-header"><span className="rank">#{String(i+1).padStart(2,'0')}</span><div className="identity"><small>{p.best.category} · Jakość <b>{p.best.quality.replace('-','−')}</b> · Fit {p.best.fit??'—'}/5</small><h2>{p.model}</h2><span className="decision">{decision(p.best)}</span></div><div className="score"><small>QUALITY-ADJUSTED B4B</small><strong>{b4b(p.best)?.toFixed(1)??'—'}</strong><span>{p.best.status}</span></div><label className="compare-select"><input type="checkbox" checked={selected.includes(p.model)} onChange={()=>toggle(p.model)}/> Porównaj <span className="sr-only">{p.model}</span></label></header><Prices o={p.best}/><h3>OFERTY I ŹRÓDŁA RYNKU ({p.offers.length})</h3>{p.offers.map(o=><Source key={o.id} offer={o} primary={o.id===p.best.id}/>)}</article>}
return <div className={'app '+density.toLowerCase()}><a className="skip" href="#results">Przejdź do wyników</a><header className="masthead"><div><p className="eyebrow">OSOBISTY WARSZTAT DECYZYJNY / 01</p><h1>PERSONAL AUDIO <span>— Deal Board</span></h1><p>Rynek w PLN · jakość oddzielona od ceny · NEW / USED / B-stock porównywane uczciwie</p></div><div className="snapshot"><b>SNAPSHOT / {snapshot.snapshot}</b><a href={snapshot.source} target="_blank" rel="noopener noreferrer" aria-label="Otwórz Google Sheets — źródło danych">Google Sheets SSOT ↗</a><small>Stan według arkusza, nie monitoring na żywo</small></div></header>
<section className="decision-strip" aria-label="Szybkie decyzje">{['Technics EAH-AZ100','Dan Clark Audio Noire X','Bose SoundLink Max'].map(model=>{const p=all.find(x=>x.model===model)!;return <button key={model} onClick={()=>{change('search',model);change('category','Wszystkie')}}><small>{decision(p.best)}</small><b>{model}</b><span>{money(p.best.price)} · {p.best.condition}</span></button>})}<div><small>PUŁAPKA CENOWA</small><b>AZ100 USED · 610 zł</b><span>13% powyżej rynku USED (540 zł)</span></div></section>
<section className="toolbar" aria-label="Filtry i sortowanie"><div className="toolbar-top"><label className="search">Szukaj modelu, sprzedawcy, kraju lub źródła<input type="search" value={f.search} onChange={e=>change('search',e.target.value)} placeholder="np. Technics, OLX, Niemcy…"/></label><label>Sortuj<select aria-label="Sortuj" value={f.sort} onChange={e=>change('sort',e.target.value)}><option value="b4b">Quality-adjusted B4B ↓</option><option value="discount">Taniej vs ten sam stan ↓</option><option value="savings">Oszczędność vs NEW ↓</option><option value="price">Cena oferty ↑</option><option value="quality">Jakość ↓</option><option value="fit">Fit ↓</option></select></label><label>Gęstość<select aria-label="Gęstość" value={density} onChange={e=>setDensity(e.target.value)}><option>Comfortable</option><option>Compact</option></select></label></div>
<div className="tabs" aria-label="Kategoria">{categories.map(c=><button key={c} aria-pressed={f.category===c} onClick={()=>change('category',c)}>{c}</button>)}</div>
<details className="filter-details" open><summary>Stan, region i dostępność</summary><div className="filter-grid"><fieldset><legend>Stan (wielokrotny wybór)</legend>{['NEW','USED','B-STOCK','OPEN-BOX','HISTORICAL'].map(c=><label key={c}><input type="checkbox" checked={f.conditions.includes(c)} onChange={()=>{change('conditions',f.conditions.includes(c)?f.conditions.filter(x=>x!==c):[...f.conditions,c]);if(c==='HISTORICAL'){change('history',true);change('liveOnly',false)}}}/>{c}</label>)}</fieldset><label>Region<select aria-label="Region" value={f.region} onChange={e=>change('region',e.target.value)}>{['Wszystkie','Polska','UE','non-EU / TLC'].map(r=><option key={r}>{r}</option>)}</select></label><label>Status<select aria-label="Status" value={f.status} onChange={e=>{change('status',e.target.value);if(e.target.value==='HISTORICAL'){change('history',true);change('liveOnly',false)}}}>{['Wszystkie','LIVE VERIFIED','LIVE USED','LEAD ONLY','HISTORICAL','NON-EU / TLC','STALE / REVERIFY'].map(s=><option key={s}>{s}</option>)}</select></label></div></details>
<div className="toggle-line"><label><input type="checkbox" checked={f.liveOnly} onChange={e=>{change('liveOnly',e.target.checked);if(e.target.checked)change('history',false)}}/>Tylko kupowalne teraz</label><label><input type="checkbox" checked={f.history} onChange={e=>{change('history',e.target.checked);if(e.target.checked)change('liveOnly',false)}}/>Pokaż historyczne benchmarki</label><button className="reset" onClick={()=>setF(defaults)}>Wyczyść filtry</button></div></section>
<main id="results" tabIndex={-1}><div className="results-heading"><p><b>{products.length}</b> modeli <span> / {products.reduce((n,p)=>n+p.offers.length,0)} źródeł</span></p><small>Jakość × rynek tego samego stanu / oferta</small></div><p role="status" className="message">{message}</p>{products.length?products.map(product):<div className="empty"><h2>Brak wyników</h2><p>Zmień filtry lub wyczyść wyszukiwanie.</p><button onClick={()=>setF(defaults)}>Pokaż wszystkie</button></div>}</main>
<footer><details><summary>Metoda i integralność danych</summary><p>B4B = QualityWeight × (rynek tego samego stanu / oferta). S 120 · S− 115 · A+ 110 · A 100 · A− 90 · B+ 80 · B 70 · B− 60 · C 50 · D 35 · E 20. Brak benchmarku oznacza brak wyniku B4B. MSRP jest wyłącznie odniesieniem.</p><p>NEW porównujemy z NEW, USED z USED, B-stock z B-stock. Lead, import bez TLC i historia nie uczestniczą w rankingu kupowalnych ofert. Fit: skala 1–5 z SSOT. Rynek PLN ma pierwszeństwo przed starszymi zakładkami. DUNU LIVE/RECENT STORE pozostaje LEAD ONLY do ponownej weryfikacji.</p><p>FX snapshot: EUR/PLN 4.37111 · GBP/PLN 5.15290 · USD/PLN 3.88344 · {snapshot.fx.timestamp}. Nie pobieramy nowych kursów w przeglądarce.</p></details><span>PERSONAL AUDIO / Źródło → analiza → decyzja</span></footer>
{selected.length>0&&<aside className="compare-dock" aria-label="Wybrane modele"><div><b>Porównanie {selected.length}/3</b><span>{selected.join(' · ')}</span></div><button ref={compareButton} onClick={()=>setComparison(true)}>Otwórz porównanie</button><button onClick={()=>{setSelected([]);setMessage('')}}>Wyczyść</button></aside>}
<dialog ref={dialog} onCancel={()=>setComparison(false)} onClose={()=>{setComparison(false);compareButton.current?.focus()}} aria-labelledby="compare-title"><header className="dialog-header"><h2 id="compare-title">Porównanie modeli</h2><button onClick={()=>setComparison(false)} autoFocus>Zamknij</button></header><div className="comparison-grid">{compare.map(p=><section key={p.model}><h3>{p.model}</h3><p>{p.best.category} · Jakość {p.best.quality} · Fit {p.best.fit??'—'}/5</p><p><b>B4B {b4b(p.best)?.toFixed(1)??'—'}</b> · {decision(p.best)}</p><Prices o={p.best}/><p>Stan: {p.best.condition} · Region: {p.best.region}</p><h4>OFERTY I ŹRÓDŁA RYNKU</h4>{p.offers.filter(o=>o.status!=='HISTORICAL'||f.history).map(o=><Source key={o.id} offer={o}/>)}</section>)}</div></dialog></div>}

